version: '3'

tasks:
  build:
    cmds:
      - python3 -m build
    silent: true
  test:
    cmds:
      - python3 -m pytest
    silent: true
  lint:
    cmds:
      - python3 -m ruff check .
    silent: true